name: "PR Checks"

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Restore yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Grant read access to private registry
        run: yarn config set --home 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Check build
        run: git diff --exit-code

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint
