name: "PR Checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version-file: ".nvmrc"

      - name: Restore yarn cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Grant read access to private registry
        run: yarn config set --home 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Check build
        run: git diff --exit-code

      - name: Format
        run: yarn format:check

      - name: Lint
        run: yarn lint
