name: "PR Checks"

on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: "Download dependencies"
        run: yarn install --frozen-lockfile

      - name: "Build"
        run: yarn build

      - name: "Synchronize self"
        id: fork-sync
        uses: ./
